name: verify

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # checkout source

      - name: Setup Python
        run: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U apio
          sudo apt install -y gtkwave

      - name: Install Apio packages
        run: apio install -a

      - name: Run verify test
        run: |
          chmox +x test.sh
          ./test.sh
